Repository StockfolioOfficial/back-landing-career, pull requests merged in 2021-09, with the labels that each got.

#107 Add: 슈퍼어드민의 어드민 삭제 및 비밀번호 수정 기능, 로그인 시 리쿠르트아이디 선택적으로 받음
  core/decorators.py
  users/admin.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: :star_struck: 리뷰 필요!, :key: STORY, :octocat: HellP

#118 Refactoring : views.py 에러 핸들링
  applications/views.py
  recruits/views.py
  users/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: HellP

#101 Add: docs 커밋 컨벤션
  Contributors.md
Labels: :memo: 문서화, :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: HellP

#116 Add : 어드민페이지 상단 대시보드
  recruits/urls.py
  recruits/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: HellP

#119 Edit: 슈퍼어드민의 어드민 정보 수정
  users/models.py
  users/serializers.py
  users/views.py
Labels: :star_struck: 리뷰 필요!, :octocat: Dodam

#109 Refactor : s3 파일 업로드 리팩토링
  README.md
  applications/views.py
  global_variable.py
  live_settings.py
Labels: :star_struck: 리뷰 필요!, :key: STORY, :octocat: Dodam

#117 Add : 어드민 페이지 채용 공고 / 어드민이 보는 채용공고 뷰 작성
  recruits/urls.py
  recruits/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK

#113 Add: 유저에 이름 추가
  users/migrations/0002_user_name.py
  users/models.py
  users/serializers.py
  users/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: Dodam

#115 Add: 첨부파일 url 보여줄 때 s3 presigned_url로 보여주기
  applications/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK

#121 Add: 관리자용 내가 올린 공고 리스트
  recruits/urls.py
  recruits/views.py
Labels: :star_struck: 리뷰 필요!, :octocat: Dodam

#128 Add: 어드민 로그인 후 지원서 열람시 로그 저장
  applications/models.py
  applications/views.py
Labels: :hammer: TASK, :octocat: luna

#130 Add: 어드민 페이지 최근 지원자 조회
  applications/models.py
  applications/urls.py
  applications/views.py
Labels: :hammer: TASK, :octocat: luna

#131 Add: 특정 공고 지원자 보기
  applications/models.py
  applications/urls.py
  applications/views.py
Labels: :monocle_face: 토론 필요!, :hammer: TASK, :octocat: luna

#133 Update(recruit): 기획에 따라 채용공고 생성에서 모집인원과 연봉 삭제
  applications/urls.py
  recruits/serializers.py
  recruits/urls.py
  recruits/views.py
  users/views.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: HellP

#136 Add: 지원서 작성시 필수 데이터 빈값 에러 반환
  applications/views.py
Labels: :hammer: TASK
