Repository StockfolioOfficial/back-landing-career, pull requests merged in 2021-08, with the labels that each got.

#23 #22 add(model migrations): 모델링 및 마이그레이션 생성
  applications/__init__.py
  applications/admin.py
  applications/apps.py
  applications/migrations/0001_initial.py
  applications/migrations/__init__.py
  applications/models.py
  applications/tests.py
  applications/views.py
  core/models.py
  recruits/__init__.py
  recruits/admin.py
  recruits/apps.py
  recruits/migrations/0001_initial.py
  recruits/migrations/__init__.py
  recruits/models.py
  recruits/tests.py
  recruits/views.py
  stockers/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: :fire: EPIC

#24 add(UserMyPageView): 회원정보 조회 및 수정
  core/decorators.py
  requirements.txt
  stockers/settings.py
  stockers/urls.py
  users/serializers.py
  users/urls.py
  users/validation.py
  users/views.py
Labels: :key: STORY

#26 #9 Add (Signup): 회원가입 EndPoint, API 구현
  requirements.txt
  stockers/settings.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: :key: STORY

#27 #10 Add (Signin): 로그인 EndPoint, API 구현
  core/decorators.py
  requirements.txt
  stockers/urls.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: :key: STORY

#28 #9 Fix (Signup): JWT 토큰 반환
  requirements.txt
  users/views.py
Labels: :hammer: TASK

#30 add(RecruitListView, RecruitView): 채용공고 목록 조회, 채용공고 상세 조회, 채용공고 생성/수정/삭제 API구현 및 문서화
  applications/models.py
  core/decorators.py
  recruits/migrations/0003_auto_20210811_1119.py
  recruits/models.py
  recruits/serializers.py
  recruits/views.py
  stockers/settings.py
  users/migrations/0002_user_role.py
  users/models.py
  users/views.py
Labels: :key: STORY

#31 add: ApplicationView => 채용 지원하기, 취소하기 // 지원서 수정하기, 삭제하기 기능 구현
  applications/serializers.py
  applications/views.py
  recruits/urls.py
Labels: :key: STORY

#32 add(VerificationView) => 비밀번호 변경 api 구현
  requirements.txt
  stockers/settings.py
  users/migrations/0002_auto_20210813_0529.py
  users/migrations/0003_alter_usertemp_table.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: :hammer: TASK

#36 fix(conventions)
  .vscode/settings.json
  applications/views.py
  recruits/views.py
  requirements.txt
  users/views.py
Labels: :hammer: TASK

#42 fix: modify env key "IS_DEBUG" -> "IS_PRODUCTION", default value "False"
  global_variable.py
  live_settings.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: yerang, :octocat: Choi MyungJun

#43 Create simple-deploy.yml
  .github/workflows/simple-deploy.yml
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: yerang, :octocat: Choi MyungJun

#45 Update simple-deploy.yml
  .github/workflows/simple-deploy.yml
Labels: :star_struck: 리뷰 필요!, :octocat: yerang, :octocat: Choi MyungJun

#61 fix: JWT_SCERET을 잘못된 곳에 설정한 부분을 정상적인 곳으로 변경
  live_settings.py
Labels: :star_struck: 리뷰 필요!, :hammer: TASK, :octocat: yerang, :octocat: Choi MyungJun

#62 swagger 장고 로그인 없애기 위한 세팅 추가
  applications/views.py
  stockers/settings.py
Labels: :bug: 버그, :octocat: Choi MyungJun

#64 fix swagger api => add static settings
  static/django_extensions/css/jquery.autocomplete.css
  static/django_extensions/img/indicator.gif
  static/django_extensions/js/jquery.ajaxQueue.js
  static/django_extensions/js/jquery.autocomplete.js
  static/django_extensions/js/jquery.bgiframe.js
  static/drf-yasg/immutable.min.js
  static/drf-yasg/insQ.min.js
  static/drf-yasg/redoc-init.js
  static/drf-yasg/redoc-old/redoc.min.js
  static/drf-yasg/redoc/redoc-logo.png
  static/drf-yasg/redoc/redoc.min.js
  static/drf-yasg/style.css
  static/drf-yasg/swagger-ui-dist/absolute-path.js
  static/drf-yasg/swagger-ui-dist/favicon-32x32.png
  static/drf-yasg/swagger-ui-dist/index.js
  static/drf-yasg/swagger-ui-dist/oauth2-redirect.html
  static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
  static/drf-yasg/swagger-ui-dist/swagger-ui-es-bundle-core.js
  static/drf-yasg/swagger-ui-dist/swagger-ui-es-bundle.js
  static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
  static/drf-yasg/swagger-ui-dist/swagger-ui.css
  static/drf-yasg/swagger-ui-init.js
  static/drf-yasg/url-polyfill.min.js
  static/rest_framework/css/bootstrap-theme.min.css
  static/rest_framework/css/bootstrap-tweaks.css
  static/rest_framework/css/bootstrap.min.css
  static/rest_framework/css/default.css
  static/rest_framework/css/font-awesome-4.0.3.css
  static/rest_framework/css/prettify.css
  static/rest_framework/docs/css/base.css
  static/rest_framework/docs/css/highlight.css
  static/rest_framework/docs/css/jquery.json-view.min.css
  static/rest_framework/docs/img/favicon.ico
  static/rest_framework/docs/img/grid.png
  static/rest_framework/docs/js/api.js
  static/rest_framework/docs/js/highlight.pack.js
  static/rest_framework/docs/js/jquery.json-view.min.js
  static/rest_framework/fonts/fontawesome-webfont.eot
  static/rest_framework/fonts/fontawesome-webfont.svg
  static/rest_framework/fonts/fontawesome-webfont.ttf
  static/rest_framework/fonts/fontawesome-webfont.woff
  static/rest_framework/fonts/glyphicons-halflings-regular.eot
  static/rest_framework/fonts/glyphicons-halflings-regular.svg
  static/rest_framework/fonts/glyphicons-halflings-regular.ttf
  static/rest_framework/fonts/glyphicons-halflings-regular.woff
  static/rest_framework/fonts/glyphicons-halflings-regular.woff2
  static/rest_framework/img/glyphicons-halflings-white.png
  static/rest_framework/img/glyphicons-halflings.png
  static/rest_framework/img/grid.png
  static/rest_framework/js/ajax-form.js
  static/rest_framework/js/bootstrap.min.js
  static/rest_framework/js/coreapi-0.1.1.js
  static/rest_framework/js/csrf.js
  static/rest_framework/js/default.js
  static/rest_framework/js/jquery-3.5.1.min.js
  static/rest_framework/js/prettify-min.js
  stockers/settings.py
Labels: :hammer: TASK, :octocat: Choi MyungJun

#74 스웨거 info 수정 및 try it out 스키마에 https 추가
  stockers/urls.py
Labels: :hammer: TASK
